### ISSUE TITLE
CoverDevice is deprecated, modify NeoSmartBlindsCover to extend CoverEntity

### ISSUE THREAD

**Issue by cjoha** [4n0nD3v3l0p3r/Home_Assistant_NeoSmartBlinds#2]
Hi there,

I'm using your custom integration with my Home Assistant installation. I can see in the HA logs that this integration is using the "CoverDevice" API. This is going to be deprecated in HA soon, and needs to be switched to using the newer "CoverEntity" API I think - see here https://developers.home-assistant.io/docs/core/entity/cover/. I'm flagging this as an issue that will likely pop up soon for other users.

**Comment by robertw** [comment]
It has stopped the loading in the current version I am not a true programmer so I am no help here sorry bu this is dead for now.
